name: First Workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'dev-*' # dev-new or dev-this-is-new any branches that start with dev
    paths:
      - './github/workflows/*'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Byeee!!"
        
